language: php

sudo: false

addons:
    apt_packages:
        - enchant

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env:
    global:
        - TEST_COMMAND="composer test"

branches:
    except:
        - /^analysis-.*$/

matrix:
    fast_finish: true
    include:
        - php: 5.5
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest --ignore-platform-reqs" COVERAGE=true TEST_COMMAND="composer test-ci"

before_install:
    - travis_retry composer self-update

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
    - pip install --user -r doc/requirements.txt

script:
    - $TEST_COMMAND
    - make -C doc SPHINXOPTS='-nW' html
    - make -C doc spelling
