language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env:
    global:
        - TEST_COMMAND="composer test"

branches:
    except:
        - /^analysis-.*$/

matrix:
    fast_finish: true
    include:
        - php: 5.4
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest --ignore-platform-reqs" COVERAGE=true TEST_COMMAND="composer test-ci"

before_install:
    - travis_retry composer self-update

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction

script:
    - $TEST_COMMAND
