name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-lowest-version:
    name: Build lowest version
    runs-on: ubuntu-latest

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@1.6.2
        with:
          php-version: '5.6'
          extensions: bcmath, gmp, intl, dom, mbstring

      - name: Set up locales
        run: |
          set -e \
          && echo en_US ISO-8859-1 | sudo tee -a /etc/locale.gen \
          && echo en_US.UTF-8 UTF-8 | sudo tee -a /etc/locale.gen \
          && echo en_CA ISO-8859-1 | sudo tee -a /etc/locale.gen \
          && echo en_CA.UTF-8 UTF-8 | sudo tee -a /etc/locale.gen \
          && echo es_ES ISO-8859-1 | sudo tee -a /etc/locale.gen \
          && echo es_ES.UTF-8 UTF-8 | sudo tee -a /etc/locale.gen \
          && echo ru_RU ISO-8859-5 | sudo tee -a /etc/locale.gen \
          && echo ru_RU.UTF-8 UTF-8 | sudo tee -a /etc/locale.gen \
          && sudo locale-gen \
          && sudo update-locale

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Download dependencies
        run: composer update --prefer-stable --prefer-lowest --prefer-dist --no-interaction

      - name: Run tests
        run: composer test

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        php: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4']
        include:
          - php: '5.6'
            composer_flags: '--prefer-stable --prefer-lowest'

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@1.6.2
        with:
          php-version: ${{ matrix.php }}
          extensions: bcmath, gmp, intl, dom, mbstring

      - name: Set up locales
        run: |
          set -e \
          && echo en_US ISO-8859-1 | sudo tee -a /etc/locale.gen \
          && echo en_US.UTF-8 UTF-8 | sudo tee -a /etc/locale.gen \
          && echo en_CA ISO-8859-1 | sudo tee -a /etc/locale.gen \
          && echo en_CA.UTF-8 UTF-8 | sudo tee -a /etc/locale.gen \
          && echo es_ES ISO-8859-1 | sudo tee -a /etc/locale.gen \
          && echo es_ES.UTF-8 UTF-8 | sudo tee -a /etc/locale.gen \
          && echo ru_RU ISO-8859-5 | sudo tee -a /etc/locale.gen \
          && echo ru_RU.UTF-8 UTF-8 | sudo tee -a /etc/locale.gen \
          && sudo locale-gen \
          && sudo update-locale

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Download dependencies
        run: composer update ${{ matrix.composer_flags }} --prefer-dist --no-interaction

      - name: Run tests
        run: composer test

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          sudo apt-get install enchant
          pip install --user -r doc/requirements.txt

      - name: Build docs
        run: |
          export PATH="/home/runner/.local/bin:$PATH"
          make -C doc SPHINXOPTS='-nW' html
          make -C doc spelling
