name: Static analysis

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install
        uses: docker://composer
        with:
          args: install --ignore-platform-reqs

      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        with:
          entrypoint: ./.github/workflows/phpstan.entrypoint
          args: analyze --no-progress

  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga:2.14.0
        with:
          args: --dry-run --diff-format udiff

  psalm:
    name: Psalm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install
        uses: docker://composer
        with:
          args: install --ignore-platform-reqs

      - name: Psalm
        uses: docker://muglug/psalm-github-actions
        with:
          entrypoint: ./.github/workflows/psalm.entrypoint
          args: --threads=8 --diff --diff-methods
